# Generated by Django 4.2.6 on 2025-06-06 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_has_min_purchase_customer_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 23, 52, 24, 360734)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 23, 52, 24, 360734)),
        ),
    ]
